---
# This workflow integrates Harness SAST and SCA with GitHub
# Visit https://docs.shiftleft.io for help
name: Harness SAST and SCA

on:
  pull_request:
  workflow_dispatch:

jobs:
  NextGen-Static-Analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Java JDK v11
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 11

    - name: Download Harness SAST and SCA CLI
      run: |
        curl https://cdn.shiftleft.io/download/sl > ${GITHUB_WORKSPACE}/sl && chmod a+rx ${GITHUB_WORKSPACE}/sl

    - name: preZero Static Analysis
      run: |
        ${GITHUB_WORKSPACE}/sl --version
        ${GITHUB_WORKSPACE}/sl analyze --strict --wait \
          --app ensemble \
          --tag branch=${{ github.head_ref }} \
          --ruby .
      env:
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
        SHIFTLEFT_API_HOST: www.shiftleft.io
        SHIFTLEFT_GRPC_TELEMETRY_HOST: telemetry.shiftleft.io:443
        SHIFTLEFT_GRPC_API_HOST: api.shiftleft.io:443

#   Build-Rules:
#     runs-on: ubuntu-latest
#     permissions: write-all
#     needs: NextGen-Static-Analysis
#     steps:
#     - uses: actions/checkout@v3
#     - name: Download Harness SAST and SCA CLI
#       run: |
#         curl https://cdn.shiftleft.io/download/sl > ${GITHUB_WORKSPACE}/sl && chmod a+rx ${GITHUB_WORKSPACE}/sl
#     - name: Validate Build Rules
#       run: |
#         ${GITHUB_WORKSPACE}/sl check-analysis --app ensemble \
#             --github-pr-number=${{github.event.number}} \
#             --github-pr-user=${{ github.repository_owner }} \
#             --github-pr-repo=${{ github.event.repository.name }} \
#             --github-token=${{ secrets.GITHUB_TOKEN }}
#       env:
#         # SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
#
#         SHIFTLEFT_API_HOST: www.shiftleft.io
#         SHIFTLEFT_GRPC_TELEMETRY_HOST: telemetry.shiftleft.io:443
#         SHIFTLEFT_GRPC_API_HOST: api.shiftleft.io:443
#
